export const popularCurrencies = [
    { code: "BRL", country: "Brasil" },
    { code: "USD", country: "Dólar EUA" },
    { code: "EUR", country: "Euro" },
    { code: "JPY", country: "Yene Japonês" },
    { code: "GBP", country: "Libra Esterlina" },
    { code: "AUD", country: "Dólar Australiano" },
    { code: "CAD", country: "Dólar Canadense" },
    { code: "CHF", country: "Franco Suíço" },
    { code: "CNY", country: "Yuan Chinês" },
    { code: "SEK", country: "Coroa Sueca" },
    { code: "NZD", country: "Dólar Neozelandês" }
];

export const currencies = [
    { code: "AED", country: "United Arab Emirates" },
    { code: "AFN", country: "Afghanistan" },
    { code: "ALL", country: "Albania" },
    { code: "AMD", country: "Armenia" },
    { code: "ANG", country: "Netherlands Antilles" },
    { code: "AOA", country: "Angola" },
    { code: "ARS", country: "Argentina" },
    { code: "AWG", country: "Aruba" },
    { code: "AZN", country: "Azerbaijan" },
    { code: "BAM", country: "Bosnia and Herzegovina" },
    { code: "BBD", country: "Barbados" },
    { code: "BDT", country: "Bangladesh" },
    { code: "BGN", country: "Bulgaria" },
    { code: "BHD", country: "Bahrain" },
    { code: "BIF", country: "Burundi" },
    { code: "BMD", country: "Bermuda" },
    { code: "BND", country: "Brunei" },
    { code: "BOB", country: "Bolivia" },
    { code: "BSD", country: "Bahamas" },
    { code: "BTN", country: "Bhutan" },
    { code: "BWP", country: "Botswana" },
    { code: "BYN", country: "Belarus" },
    { code: "BZD", country: "Belize" },
    { code: "CDF", country: "Democratic Republic of the Congo" },
    { code: "CLP", country: "Chile" },
    { code: "COP", country: "Colombia" },
    { code: "CRC", country: "Costa Rica" },
    { code: "CUP", country: "Cuba" },
    { code: "CVE", country: "Cape Verde" },
    { code: "CZK", country: "Czech Republic" },
    { code: "DJF", country: "Djibouti" },
    { code: "DKK", country: "Denmark" },
    { code: "DOP", country: "Dominican Republic" },
    { code: "DZD", country: "Algeria" },
    { code: "EGP", country: "Egypt" },
    { code: "ERN", country: "Eritrea" },
    { code: "ETB", country: "Ethiopia" },
    { code: "FJD", country: "Fiji" },
    { code: "FKP", country: "Falkland Islands" },
    { code: "FOK", country: "Faroe Islands" },
    { code: "GEL", country: "Georgia" },
    { code: "GGP", country: "Guernsey" },
    { code: "GHS", country: "Ghana" },
    { code: "GIP", country: "Gibraltar" },
    { code: "GMD", country: "The Gambia" },
    { code: "GNF", country: "Guinea" },
    { code: "GTQ", country: "Guatemala" },
    { code: "GYD", country: "Guyana" },
    { code: "HKD", country: "Hong Kong" },
    { code: "HNL", country: "Honduras" },
    { code: "HRK", country: "Croatia" },
    { code: "HTG", country: "Haiti" },
    { code: "HUF", country: "Hungary" },
    { code: "IDR", country: "Indonesia" },
    { code: "ILS", country: "Israel" },
    { code: "IMP", country: "Isle of Man" },
    { code: "INR", country: "India" },
    { code: "IQD", country: "Iraq" },
    { code: "IRR", country: "Iran" },
    { code: "ISK", country: "Iceland" },
    { code: "JEP", country: "Jersey" },
    { code: "JMD", country: "Jamaica" },
    { code: "JOD", country: "Jordan" },
    { code: "KES", country: "Kenya" },
    { code: "KGS", country: "Kyrgyzstan" },
    { code: "KHR", country: "Cambodia" },
    { code: "KID", country: "Kiribati" },
    { code: "KMF", country: "Comoros" },
    { code: "KRW", country: "South Korea" },
    { code: "KWD", country: "Kuwait" },
    { code: "KYD", country: "Cayman Islands" },
    { code: "KZT", country: "Kazakhstan" },
    { code: "LAK", country: "Laos" },
    { code: "LBP", country: "Lebanon" },
    { code: "LKR", country: "Sri Lanka" },
    { code: "LRD", country: "Liberia" },
    { code: "LSL", country: "Lesotho" },
    { code: "LYD", country: "Libya" },
    { code: "MAD", country: "Morocco" },
    { code: "MDL", country: "Moldova" },
    { code: "MGA", country: "Madagascar" },
    { code: "MKD", country: "North Macedonia" },
    { code: "MMK", country: "Myanmar" },
    { code: "MNT", country: "Mongolia" },
    { code: "MOP", country: "Macau" },
    { code: "MRU", country: "Mauritania" },
    { code: "MUR", country: "Mauritius" },
    { code: "MVR", country: "Maldives" },
    { code: "MWK", country: "Malawi" },
    { code: "MXN", country: "Mexico" },
    { code: "MYR", country: "Malaysia" },
    { code: "MZN", country: "Mozambique" },
    { code: "NAD", country: "Namibia" },
    { code: "NGN", country: "Nigeria" },
    { code: "NIO", country: "Nicaragua" },
    { code: "NOK", country: "Norway" },
    { code: "NPR", country: "Nepal" },
    { code: "OMR", country: "Oman" },
    { code: "PAB", country: "Panama" },
    { code: "PEN", country: "Peru" },
    { code: "PGK", country: "Papua New Guinea" },
    { code: "PHP", country: "Philippines" },
    { code: "PKR", country: "Pakistan" },
    { code: "PLN", country: "Poland" },
    { code: "PYG", country: "Paraguay" },
    { code: "QAR", country: "Qatar" },
    { code: "RON", country: "Romania" },
    { code: "RSD", country: "Serbia" },
    { code: "RUB", country: "Russia" },
    { code: "RWF", country: "Rwanda" },
    { code: "SAR", country: "Saudi Arabia" },
    { code: "SBD", country: "Solomon Islands" },
    { code: "SCR", country: "Seychelles" },
    { code: "SDG", country: "Sudan" },
    { code: "SGD", country: "Singapore" },
    { code: "SHP", country: "Saint Helena" },
    { code: "SLE", country: "Sierra Leone" },
    { code: "SOS", country: "Somalia" },
    { code: "SRD", country: "Suriname" },
    { code: "SSP", country: "South Sudan" },
    { code: "STN", country: "São Tomé and Príncipe" },
    { code: "SYP", country: "Syria" },
    { code: "SZL", country: "Eswatini" },
    { code: "THB", country: "Thailand" },
    { code: "TJS", country: "Tajikistan" },
    { code: "TMT", country: "Turkmenistan" },
    { code: "TND", country: "Tunisia" },
    { code: "TOP", country: "Tonga" },
    { code: "TRY", country: "Turkey" },
    { code: "TTD", country: "Trinidad and Tobago" },
    { code: "TVD", country: "Tuvalu" },
    { code: "TWD", country: "Taiwan" },
    { code: "TZS", country: "Tanzania" },
    { code: "UAH", country: "Ukraine" },
    { code: "UGX", country: "Uganda" },
    { code: "UYU", country: "Uruguay" },
    { code: "UZS", country: "Uzbekistan" },
    { code: "VES", country: "Venezuela" },
    { code: "VND", country: "Vietnam" },
    { code: "VUV", country: "Vanuatu" },
    { code: "WST", country: "Samoa" },
    { code: "XAF", country: "Central African CFA Franc" },
    { code: "XCD", country: "East Caribbean Dollar" },
    { code: "XOF", country: "West African CFA Franc" },
    { code: "XPF", country: "CFP Franc" },
    { code: "YER", country: "Yemen" },
    { code: "ZAR", country: "South Africa" },
    { code: "ZMW", country: "Zambia" },
    { code: "ZWL", country: "Zimbabwe" }
];