import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Navbar from "@/components/navbar";

const darkGrotesque = Darker_Grotesque({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Utools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={darkGrotesque.className}>
        <SidebarProvider>
          <AppSidebar/>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="flex flex-col min-h-screen w-full">
              <Navbar/>
              {children}
            </div>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
