import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Utools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <SidebarProvider>
          <AppSidebar/>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SidebarTrigger />
            {children}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
